apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - omc-app-placementrule.yaml
  - omc-pipeline-placementrule.yaml
  - omc-pipeline-subscription.yaml
  - omc-pipeline-application.yaml