apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: omc-pipeline-policy
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: In, values: ["true"]}