apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: omc-app-pipeline
  namespace: omc-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - omc-pipeline