apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: omc-sa-rolebinding
  namespace: openshift-mini-console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-mini-console-sa-role
subjects:
  - kind: ServiceAccount
    name: openshift-mini-console-sa
    namespace: openshift-mini-console