apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: route53-record-update
  namespace: omc-app
  labels:
    app.kubernetes.io/name: omc-app
spec:
  tower_auth_secret: toweraccess
  job_template_name: route53-record-update